name: Deploy Node.js to Azure

env:
  AZURE_WEBAPP_NAME: 'node-api-sqlite'    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root


on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}


    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Set this to your app's version
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm install
          npm install better-sqlite3
          npm run build --if-present

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 # Check for v4 if available in 2026
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          clean: false